/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLocation.java
 *
 * Created on Jan 12, 2011, 8:58:37 PM
 */
package com.ray.astro.ui;

import com.ray.astro.db.LocationDAO;
import com.ray.astro.app.AstroRayAppException;
import com.ray.astro.app.AstroRayApplication;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Family
 */
public class DlgLocation extends javax.swing.JDialog {

    LocationDAO locationDAO;

    String currentLocation;
    String currentLatitude;
    String currentLongitude;

    /** Creates new form DlgLocation */
    public DlgLocation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Set txfLatitude field format
        ((javax.swing.text.MaskFormatter) txfLatitude.getFormatter()).setValidCharacters("0123456789nsNS");

        //Set txfLongitude field format for
        ((javax.swing.text.MaskFormatter) txfLongitude.getFormatter()).setValidCharacters("0123456789ewEW");

        FrmBirthData frmBirthData = (FrmBirthData) this.getParent();
        AstroRayApplication application = frmBirthData.getApplication();
        locationDAO = application.getLocationDAO();
        
        btnShowAllActionPerformed(null);
    }

    private void clearTextFields() {
        txtLocation.setText("");
        txfLatitude.setText("00:00:00:N");
        txfLongitude.setText("00:00:00:E");
    }

    private void clearLatitudeAndLongitude() {
        txfLatitude.setText("00:00:00:N");
        txfLongitude.setText("00:00:00:E");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        pnlLocation = new javax.swing.JPanel();
        txtLocation = new javax.swing.JTextField();
        lblLongitude = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        txfLongitude = new javax.swing.JFormattedTextField();
        txfLatitude = new javax.swing.JFormattedTextField();
        lblLongitude1 = new javax.swing.JLabel();
        scrLocations = new javax.swing.JScrollPane();
        lstLocations = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Location Details");
        setModal(true);
        setName(""); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnSearch.setMnemonic('e');
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSelect.setMnemonic('l');
        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnShowAll.setMnemonic('h');
        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnModify.setMnemonic('M');
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnAdd.setMnemonic('A');
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        pnlLocation.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));
        pnlLocation.setFont(new java.awt.Font("Tahoma", 0, 12));
        pnlLocation.setPreferredSize(new java.awt.Dimension(500, 143));

        txtLocation.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtLocation.setMinimumSize(new java.awt.Dimension(350, 21));
        txtLocation.setPreferredSize(new java.awt.Dimension(66, 24));
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        txtLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLocationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLocationFocusLost(evt);
            }
        });

        lblLongitude.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblLongitude.setText("Longitude (DD:MM:SS:E|W)");
        lblLongitude.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblLongitude.setPreferredSize(new java.awt.Dimension(60, 15));

        lblLatitude.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblLatitude.setText("Latitude (DD:MM:SS:N|S)");
        lblLatitude.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblLatitude.setMaximumSize(new java.awt.Dimension(153, 15));
        lblLatitude.setMinimumSize(new java.awt.Dimension(153, 15));
        lblLatitude.setPreferredSize(new java.awt.Dimension(60, 15));

        try {
            txfLongitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##:U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfLongitude.setFont(new java.awt.Font("Tahoma", 0, 12));
        txfLongitude.setPreferredSize(new java.awt.Dimension(38, 24));
        txfLongitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfLongitudeFocusGained(evt);
            }
        });

        try {
            txfLatitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##:U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfLatitude.setFont(new java.awt.Font("Tahoma", 0, 12));
        txfLatitude.setPreferredSize(new java.awt.Dimension(38, 24));
        txfLatitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfLatitudeFocusGained(evt);
            }
        });

        lblLongitude1.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblLongitude1.setText("=");
        lblLongitude1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblLongitude1.setPreferredSize(new java.awt.Dimension(60, 15));

        javax.swing.GroupLayout pnlLocationLayout = new javax.swing.GroupLayout(pnlLocation);
        pnlLocation.setLayout(pnlLocationLayout);
        pnlLocationLayout.setHorizontalGroup(
            pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(lblLongitude1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLocationLayout.createSequentialGroup()
                            .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txfLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLocationLayout.setVerticalGroup(
            pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLocationLayout.createSequentialGroup()
                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLongitude1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        lstLocations.setFont(new java.awt.Font("Tahoma", 0, 12));
        lstLocations.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLocations.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstLocationsValueChanged(evt);
            }
        });
        scrLocations.setViewportView(lstLocations);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrLocations, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModify, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(btnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrLocations, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelect)
                    .addComponent(btnShowAll)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        try {
            clearLatitudeAndLongitude();
            txtLocation.setText(txtLocation.getText().toUpperCase().trim());
            String location = txtLocation.getText();

            DefaultListModel model = new DefaultListModel();

            Vector vecLocations = locationDAO.getMatchingLocations(location);
            if (vecLocations != null) {
                for (int i = 0; i < vecLocations.size(); i++) {
                    model.addElement(vecLocations.elementAt(i));
                }
                model.trimToSize();
            }

            lstLocations.setModel(model);

            lstLocations.clearSelection();

            if (!model.isEmpty()) {
                if (location.contains("%")) {
                    lstLocations.setSelectedIndex(0);
                    lstLocations.ensureIndexIsVisible(0);
                } else {
                    lstLocations.setSelectedValue(location, true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No matching records found");
            }
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        try {
            String location = txtLocation.getText().trim().toUpperCase();
            String latitude = txfLatitude.getText();
            String longitude = txfLongitude.getText();
            if (!location.equals("") && !latitude.startsWith("00:00:00") && !longitude.startsWith("00:00:00")) {
                locationDAO.addLocation(location, latitude, longitude);
                JOptionPane.showMessageDialog(this, "Location " + location + " got added successfully");
                DefaultListModel model = (DefaultListModel) lstLocations.getModel();
                model.add(0, location);
                model.trimToSize();
                lstLocations.setSelectedIndex(0);
                lstLocations.ensureIndexIsVisible(0);
            } else {
                JOptionPane.showMessageDialog(this, "Enter valid values");
            }
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnAddActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed

        try {
            clearTextFields();            
            lstLocations.setSelectedIndex(-1);

            DefaultListModel model = new DefaultListModel();

            Vector vecLocations = locationDAO.getAllLocations();
            if (vecLocations != null) {
                for (int i = 0; i < vecLocations.size(); i++) {
                    model.addElement(vecLocations.elementAt(i));
                }
                model.trimToSize();
            }

            lstLocations.setModel(model);

            if (!model.isEmpty()) {
                lstLocations.setSelectedIndex(0);
                lstLocations.ensureIndexIsVisible(0);
            } else {
                JOptionPane.showMessageDialog(this, "No records found");
            }
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed

        String location = txtLocation.getText().trim().toUpperCase();
        String latitude = txfLatitude.getText();
        String longitude = txfLongitude.getText();
        if (!location.equals("") && !latitude.startsWith("00:00:00") && !longitude.startsWith("00:00:00")) {
            ((FrmBirthData) this.getParent()).setLocLatLon(location, latitude, longitude);
            this.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Selection");
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed

        try {
            String oldLocation = lstLocations.getSelectedValue().toString();
            String newLocation = txtLocation.getText().trim().toUpperCase();
            String latitude = txfLatitude.getText();
            String longitude = txfLongitude.getText();

            if (!newLocation.equals("") && !latitude.startsWith("00:00:00") && !longitude.startsWith("00:00:00")) {

                if (newLocation.equals(currentLocation) && latitude.equals(currentLatitude) && longitude.equals(currentLongitude)) {
                    JOptionPane.showMessageDialog(this, "No Modifications found");
                    return;
                }
                
                int modifyingIndex = lstLocations.getSelectedIndex();

                locationDAO.modifyLocation(oldLocation, newLocation, latitude, longitude);
                JOptionPane.showMessageDialog(this, "Location " + newLocation + " got modified successfully");

                DefaultListModel model = (DefaultListModel) lstLocations.getModel();
                model.setElementAt(newLocation, modifyingIndex);
                model.trimToSize();

                lstLocations.setSelectedIndex(modifyingIndex);
                lstLocations.ensureIndexIsVisible(modifyingIndex);
            } else {
                JOptionPane.showMessageDialog(this, "Enter valid values");
            }
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        try {
            String location = (String) lstLocations.getSelectedValue();
            int selectedIndex = lstLocations.getSelectedIndex();

            if (location == null || selectedIndex == -1) {
                JOptionPane.showMessageDialog(this, "No records to delete");
                return;
            }

            int reply = JOptionPane.showConfirmDialog(this, "Do you really want to Delete?");

            if (reply == JOptionPane.CANCEL_OPTION || reply == JOptionPane.NO_OPTION) {
                return;
            }

            locationDAO.deleteLocation(location);

            DefaultListModel model = (DefaultListModel) lstLocations.getModel();
            model.removeElement(location);
            model.trimToSize();

            if (!model.isEmpty()) {
                if (model.size() == selectedIndex) {
                    selectedIndex = model.size() - 1;
                }
                lstLocations.setSelectedIndex(selectedIndex);
                lstLocations.ensureIndexIsVisible(selectedIndex);

            } else {
                clearTextFields();
            }

            JOptionPane.showMessageDialog(this, "Location " + location + " got deleted successfully");
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        btnSearchActionPerformed(null);
}//GEN-LAST:event_txtLocationActionPerformed

    private void txtLocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLocationFocusGained
        txtLocation.setCaretPosition(0);
        txtLocation.selectAll();
}//GEN-LAST:event_txtLocationFocusGained

    private void lstLocationsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstLocationsValueChanged

        try {
            if (lstLocations.getSelectedIndex() < 0) {
                clearTextFields();
                return;
            }
            
            String location = (String)lstLocations.getSelectedValue();

            if (location == null) {
                clearTextFields();
                return;
            }

            location = location.toString().trim();

            if (location.equals("")) {
                clearTextFields();
                return;
            }
            
            String[] latLon = locationDAO.getLatitudeAndLongitude(location);
            if (latLon != null) {
                txtLocation.setText(location);
                txfLatitude.setText(latLon[0]);
                txfLongitude.setText(latLon[1]);

                currentLocation = location;
                currentLatitude = latLon[0];
                currentLongitude = latLon[1];
            }
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_lstLocationsValueChanged

    private void txfLatitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfLatitudeFocusGained

        txfLatitude.setCaretPosition(0);
    }//GEN-LAST:event_txfLatitudeFocusGained

    private void txfLongitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfLongitudeFocusGained

        txfLongitude.setCaretPosition(0);
    }//GEN-LAST:event_txfLongitudeFocusGained

    private void txtLocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLocationFocusLost

        txtLocation.setText(txtLocation.getText().toUpperCase().trim());
    }//GEN-LAST:event_txtLocationFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        btnCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DlgLocation dialog = new DlgLocation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblLongitude1;
    private javax.swing.JList lstLocations;
    private javax.swing.JPanel pnlLocation;
    private javax.swing.JScrollPane scrLocations;
    private javax.swing.JFormattedTextField txfLatitude;
    private javax.swing.JFormattedTextField txfLongitude;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
