/*
 * FrmAstroGUI.java
 *
 * Created on April 4, 2008, 10:50 PM
 */
package com.ray.astro.ui;

import com.ray.astro.app.AstroRayAppException;
import com.ray.astro.app.AstroRayApplication;
import com.ray.astro.model.BirthData;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author  Rayan Ivaturi
 */
public class FrmBirthData extends javax.swing.JFrame {

    /** Reference to the Main Application */
    private AstroRayApplication application;

    /** Creates new form FrmAstroGUI */
    public FrmBirthData() {
        initComponents();
    }

    public FrmBirthData(AstroRayApplication application) {
        this.application = application;
        initComponents();

        //Set txfTime field format for AM and PM
        ((javax.swing.text.MaskFormatter) txfTime.getFormatter()).setValidCharacters("0123456789apmAPM");

        //Set txfLatitude field format for AM and PM
        ((javax.swing.text.MaskFormatter) txfLatitude.getFormatter()).setValidCharacters("0123456789nsNS");

        //Set txfLongitude field format for AM and PM
        ((javax.swing.text.MaskFormatter) txfLongitude.getFormatter()).setValidCharacters("0123456789ewEW");

        //Set txfTimeZone field format for + and -
        ((javax.swing.text.MaskFormatter) txfTimeZone.getFormatter()).setValidCharacters("0123456789+-");

        //Get Current Date and Time
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss:a");
        String dateNTime = sdf.format(calendar.getTime());

        //Set Current Date and Time
        String[] dateTimeToken = dateNTime.split(" ");
        txfDate.setText(dateTimeToken[0]);
        txfTime.setText(dateTimeToken[1]);

        //Set Default Location
        txtLocation.setText("HYDERABAD");

        //Initialize Latitude & Longitude
        txfLatitude.setText("00:00:00:N");
        txfLongitude.setText("00:00:00:E");

        //Set Default Time Zone to India
        chkTimeZone.setSelected(false);
        txfTimeZone.setText("+ 05:30:00");
        txfTimeZone.setEnabled(false);

        //Set Default Day Light Saving to Zero
        chkDST.setSelected(false);
        txfDST.setText("00:00:00");
        txfDST.setEnabled(false);

        chkMoon.setSelected(false);
        txfMoon.setText("00:00:00:00");
        txfMoon.setEnabled(false);

        //Initiate Database and set Default Latitude & Longitude
        try {
            application.getLocationDAO().initDB();
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        txtLocationActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlName = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        pnlDateAndTime = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        txfDate = new javax.swing.JFormattedTextField();
        lblTime = new javax.swing.JLabel();
        txfTime = new javax.swing.JFormattedTextField();
        pnlLocation = new javax.swing.JPanel();
        txtLocation = new javax.swing.JTextField();
        lblLongitude = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        txfLongitude = new javax.swing.JFormattedTextField();
        txfLatitude = new javax.swing.JFormattedTextField();
        lblLongitude1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        pnlTimeZoneAndMoon = new javax.swing.JPanel();
        txfTimeZone = new javax.swing.JFormattedTextField();
        txfDST = new javax.swing.JFormattedTextField();
        chkDST = new javax.swing.JCheckBox();
        chkMoon = new javax.swing.JCheckBox();
        txfMoon = new javax.swing.JFormattedTextField();
        chkTimeZone = new javax.swing.JCheckBox();
        pnlRemarks = new javax.swing.JPanel();
        scrRemarks = new javax.swing.JScrollPane();
        txaRemarks = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AstroRay");
        setMinimumSize(new java.awt.Dimension(350, 665));
        setName(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Name"));
        pnlName.setFont(new java.awt.Font("Tahoma", 0, 12));
        pnlName.setPreferredSize(new java.awt.Dimension(500, 73));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtName.setMinimumSize(new java.awt.Dimension(200, 21));
        txtName.setPreferredSize(new java.awt.Dimension(66, 24));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlNameLayout = new javax.swing.GroupLayout(pnlName);
        pnlName.setLayout(pnlNameLayout);
        pnlNameLayout.setHorizontalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNameLayout.setVerticalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameLayout.createSequentialGroup()
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDateAndTime.setBorder(javax.swing.BorderFactory.createTitledBorder("Date and Time"));
        pnlDateAndTime.setFont(new java.awt.Font("Tahoma", 0, 12));
        pnlDateAndTime.setPreferredSize(new java.awt.Dimension(500, 95));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblDate.setText("Date (DD-MM-YYYY)");
        lblDate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblDate.setMaximumSize(new java.awt.Dimension(153, 15));
        lblDate.setMinimumSize(new java.awt.Dimension(153, 15));
        lblDate.setPreferredSize(new java.awt.Dimension(60, 15));

        try {
            txfDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfDate.setFont(new java.awt.Font("Tahoma", 0, 12));
        txfDate.setPreferredSize(new java.awt.Dimension(38, 24));
        txfDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfDateFocusGained(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblTime.setText("Time (HH:MM:SS:AM|PM)");
        lblTime.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTime.setMaximumSize(new java.awt.Dimension(153, 15));
        lblTime.setMinimumSize(new java.awt.Dimension(153, 15));
        lblTime.setPreferredSize(new java.awt.Dimension(60, 15));

        try {
            txfTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##:UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfTime.setFont(new java.awt.Font("Tahoma", 0, 12));
        txfTime.setPreferredSize(new java.awt.Dimension(38, 24));
        txfTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfTimeFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlDateAndTimeLayout = new javax.swing.GroupLayout(pnlDateAndTime);
        pnlDateAndTime.setLayout(pnlDateAndTimeLayout);
        pnlDateAndTimeLayout.setHorizontalGroup(
            pnlDateAndTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateAndTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDateAndTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDateAndTimeLayout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDateAndTimeLayout.createSequentialGroup()
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(254, 254, 254))
        );
        pnlDateAndTimeLayout.setVerticalGroup(
            pnlDateAndTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateAndTimeLayout.createSequentialGroup()
                .addGroup(pnlDateAndTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDateAndTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pnlLocation.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));
        pnlLocation.setFont(new java.awt.Font("Tahoma", 0, 12));
        pnlLocation.setPreferredSize(new java.awt.Dimension(500, 143));

        txtLocation.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtLocation.setMinimumSize(new java.awt.Dimension(350, 21));
        txtLocation.setPreferredSize(new java.awt.Dimension(66, 24));
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        txtLocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLocationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLocationFocusLost(evt);
            }
        });

        lblLongitude.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLongitude.setText("Longitude (DD:MM:SS:E|W)");
        lblLongitude.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblLongitude.setPreferredSize(new java.awt.Dimension(60, 15));

        lblLatitude.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblLatitude.setText("Latitude (DD:MM:SS:N|S)");
        lblLatitude.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblLatitude.setMaximumSize(new java.awt.Dimension(153, 15));
        lblLatitude.setMinimumSize(new java.awt.Dimension(153, 15));
        lblLatitude.setPreferredSize(new java.awt.Dimension(60, 15));

        try {
            txfLongitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##:U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfLongitude.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txfLongitude.setPreferredSize(new java.awt.Dimension(38, 24));
        txfLongitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfLongitudeFocusGained(evt);
            }
        });

        try {
            txfLatitude.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##:U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfLatitude.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txfLatitude.setPreferredSize(new java.awt.Dimension(38, 24));
        txfLatitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfLatitudeFocusGained(evt);
            }
        });

        lblLongitude1.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblLongitude1.setText("=");
        lblLongitude1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblLongitude1.setPreferredSize(new java.awt.Dimension(60, 15));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLocationLayout = new javax.swing.GroupLayout(pnlLocation);
        pnlLocation.setLayout(pnlLocationLayout);
        pnlLocationLayout.setHorizontalGroup(
            pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(lblLongitude1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlLocationLayout.setVerticalGroup(
            pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLocationLayout.createSequentialGroup()
                .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(lblLongitude1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlLocationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pnlTimeZoneAndMoon.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Zone & Moon"));
        pnlTimeZoneAndMoon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pnlTimeZoneAndMoon.setPreferredSize(new java.awt.Dimension(500, 128));

        try {
            txfTimeZone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("* ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfTimeZone.setFont(new java.awt.Font("Tahoma", 0, 12));
        txfTimeZone.setPreferredSize(new java.awt.Dimension(38, 24));
        txfTimeZone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfTimeZoneFocusGained(evt);
            }
        });

        try {
            txfDST.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfDST.setEnabled(false);
        txfDST.setFont(new java.awt.Font("Tahoma", 0, 12));
        txfDST.setPreferredSize(new java.awt.Dimension(38, 24));
        txfDST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDSTActionPerformed(evt);
            }
        });

        chkDST.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkDST.setText("DST (HH:MM:SS)");
        chkDST.setMaximumSize(new java.awt.Dimension(153, 15));
        chkDST.setMinimumSize(new java.awt.Dimension(153, 15));
        chkDST.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDSTItemStateChanged(evt);
            }
        });
        chkDST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDSTActionPerformed(evt);
            }
        });

        chkMoon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkMoon.setText("Moon (SS:DD:MM:SS)");
        chkMoon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkMoonItemStateChanged(evt);
            }
        });
        chkMoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMoonActionPerformed(evt);
            }
        });

        try {
            txfMoon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfMoon.setEnabled(false);
        txfMoon.setFont(new java.awt.Font("Tahoma", 0, 12));
        txfMoon.setPreferredSize(new java.awt.Dimension(38, 24));
        txfMoon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfMoonFocusGained(evt);
            }
        });

        chkTimeZone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkTimeZone.setText("Time Zone (-|+ HH:MM:SS)");
        chkTimeZone.setMaximumSize(new java.awt.Dimension(153, 15));
        chkTimeZone.setMinimumSize(new java.awt.Dimension(153, 15));
        chkTimeZone.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkTimeZoneItemStateChanged(evt);
            }
        });
        chkTimeZone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTimeZoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTimeZoneAndMoonLayout = new javax.swing.GroupLayout(pnlTimeZoneAndMoon);
        pnlTimeZoneAndMoon.setLayout(pnlTimeZoneAndMoonLayout);
        pnlTimeZoneAndMoonLayout.setHorizontalGroup(
            pnlTimeZoneAndMoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimeZoneAndMoonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTimeZoneAndMoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkTimeZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkMoon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTimeZoneAndMoonLayout.createSequentialGroup()
                        .addComponent(chkDST, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTimeZoneAndMoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfMoon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTimeZone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDST, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        pnlTimeZoneAndMoonLayout.setVerticalGroup(
            pnlTimeZoneAndMoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimeZoneAndMoonLayout.createSequentialGroup()
                .addGroup(pnlTimeZoneAndMoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMoon)
                    .addComponent(txfMoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTimeZoneAndMoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTimeZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTimeZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTimeZoneAndMoonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlRemarks.setBorder(javax.swing.BorderFactory.createTitledBorder("Remarks"));
        pnlRemarks.setFont(new java.awt.Font("Tahoma", 0, 12));
        pnlRemarks.setPreferredSize(new java.awt.Dimension(500, 122));

        txaRemarks.setColumns(20);
        txaRemarks.setFont(new java.awt.Font("Tahoma", 0, 12));
        txaRemarks.setRows(5);
        scrRemarks.setViewportView(txaRemarks);

        javax.swing.GroupLayout pnlRemarksLayout = new javax.swing.GroupLayout(pnlRemarks);
        pnlRemarks.setLayout(pnlRemarksLayout);
        pnlRemarksLayout.setHorizontalGroup(
            pnlRemarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemarksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRemarksLayout.setVerticalGroup(
            pnlRemarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemarksLayout.createSequentialGroup()
                .addComponent(scrRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setMnemonic('O');
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnlRemarks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                        .addComponent(pnlTimeZoneAndMoon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                        .addComponent(pnlLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                        .addComponent(pnlDateAndTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                        .addComponent(pnlName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTimeZoneAndMoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(pnlRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlTimeZoneAndMoon.getAccessibleContext().setAccessibleName("Time ZoneAndMoon");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private BirthData getBirthData() {
        BirthData birthData = new BirthData();

        birthData.setName(txtName.getText());

        String[] dateTokens = txfDate.getText().split("-");
        birthData.setDay(Integer.parseInt(dateTokens[0]));
        birthData.setMonth(Integer.parseInt(dateTokens[1]));
        birthData.setYear(Integer.parseInt(dateTokens[2]));
        
        String[] timeTokens = txfTime.getText().split(":");
        birthData.setHours(Integer.parseInt(timeTokens[0]));
        birthData.setMinutes(Integer.parseInt(timeTokens[1]));
        birthData.setSeconds(Integer.parseInt(timeTokens[2]));
        birthData.setMeridian(timeTokens[3]);

        birthData.setLocationName(txtLocation.getText());

        
        String[] latitudeTokens = txfLatitude.getText().split(":");
        birthData.setLatitudeDegrees(Integer.parseInt(latitudeTokens[0]));
        birthData.setLatitudeMinutes(Integer.parseInt(latitudeTokens[1]));
        birthData.setLatitudeSeconds(Integer.parseInt(latitudeTokens[2]));
        if (latitudeTokens[3].equalsIgnoreCase("N")) {
            birthData.setLatitudeDirection(BirthData.NORTH);
        } else if (latitudeTokens[3].equalsIgnoreCase("S")) {
            birthData.setLatitudeDirection(BirthData.SOUTH);
        }

       
        String[] longitudeTokens = txfLongitude.getText().split(":");
        birthData.setLongitudeDegrees(Integer.parseInt(longitudeTokens[0]));
        birthData.setLongitudeMinutes(Integer.parseInt(longitudeTokens[1]));
        birthData.setLongitudeSeconds(Integer.parseInt(longitudeTokens[2]));
        if (longitudeTokens[3].equalsIgnoreCase("E")) {
            birthData.setLongitudeDirection(BirthData.EAST);
        } else if (longitudeTokens[3].equalsIgnoreCase("W")) {
            birthData.setLongitudeDirection(BirthData.WEST);
        }

        String[] timeZoneTokens = txfTimeZone.getText().split(":");
        if (timeZoneTokens[0].charAt(0) == '+') {
            birthData.setTimeZoneDirection(BirthData.EAST);
        } else {
            birthData.setTimeZoneDirection(BirthData.WEST);
        }        
        birthData.setTimeZoneHours(Integer.parseInt(timeZoneTokens[0].substring(2, 4)));
        birthData.setTimeZoneMinutes(Integer.parseInt(timeZoneTokens[1]));
        birthData.setTimeZoneSeconds(Integer.parseInt(timeZoneTokens[2]));

        birthData.setInDST(chkDST.isSelected());        
        String[] dstTokens = txfDST.getText().split(":");
        birthData.setDstHours(Integer.parseInt(dstTokens[0]));
        birthData.setDstMinutes(Integer.parseInt(dstTokens[1]));
        birthData.setDstSeconds(Integer.parseInt(dstTokens[2]));

        birthData.setIsMoonGiven(chkMoon.isSelected());        
        String[] moonTokens = txfMoon.getText().split(":");
        birthData.setMoonSign(Integer.parseInt(moonTokens[0]));
        birthData.setMoonDegrees(Integer.parseInt(moonTokens[1]));
        birthData.setMoonMinutes(Integer.parseInt(moonTokens[2]));
        birthData.setMoonSeconds(Integer.parseInt(moonTokens[3]));

        birthData.setRemarks(txaRemarks.getText());

        return birthData;
    }

    public AstroRayApplication getApplication() {
        return application;
    }

    private void clearLatitudeAndLogitude() {
        txfLatitude.setText("00:00:00:N");
        txfLongitude.setText("00:00:00:E");
    }

    private void setLatitudeAndLogitude(String location) {
        try {
            txtLocation.setText(location);

            String[] latLon = application.getLocationDAO().getLatitudeAndLongitude(location);
            if (latLon == null) {
                clearLatitudeAndLogitude();
                JOptionPane.showMessageDialog(this, "Location " + location + " not found in the Database");
            } else {
                txfLatitude.setText(latLon[0]);
                txfLongitude.setText(latLon[1]);
            }
        } catch (AstroRayAppException e) {
            clearLatitudeAndLogitude();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void setLocLatLon(String location, String latitude, String longitude) {
        txtLocation.setText(location);
        txfLatitude.setText(latitude);
        txfLongitude.setText(longitude);
    }

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try {
            String message = application.prepareHoroscope(getBirthData());
            JOptionPane.showMessageDialog(this, message);

            //Store the Location details in astroray_latlon.dat file if not found
            try {
                if (application.getLocationDAO().getMatchingLocations(txtLocation.getText().trim().toUpperCase()) == null) {
                    application.getLocationDAO().addLocation(txtLocation.getText().trim().toUpperCase(), txfLatitude.getText().trim(), txfLongitude.getText().trim());
                }
            } catch (AstroRayAppException aep) {
                JOptionPane.showMessageDialog(this, aep.getMessage());
            }

            //View the PDF file using Adobe Acrobat Reader
            application.viewPdfFile();

        } catch (AstroRayAppException ae) {
            JOptionPane.showMessageDialog(null, ae.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        try {
            application.getLocationDAO().closeDB();
        } catch (AstroRayAppException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Not able to close Database Connection", JOptionPane.ERROR_MESSAGE);
        }
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        txtLocation.setText(txtLocation.getText().toUpperCase().trim());
        String location = txtLocation.getText();
        setLatitudeAndLogitude(location);
}//GEN-LAST:event_txtLocationActionPerformed

private void chkDSTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDSTItemStateChanged

    if (evt.getStateChange() == ItemEvent.DESELECTED) {
        txfDST.setText("00:00:00");
        txfDST.setEnabled(false);
    } else {
        txfDST.setText("01:00:00");
        txfDST.setEnabled(true);
    }

}//GEN-LAST:event_chkDSTItemStateChanged

private void chkMoonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkMoonItemStateChanged

    if (evt.getStateChange() == ItemEvent.DESELECTED) {
        txfMoon.setText("00:00:00:00");
        txfMoon.setEnabled(false);
    } else {
        txfMoon.setEnabled(true);
    }
}//GEN-LAST:event_chkMoonItemStateChanged

private void chkMoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMoonActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_chkMoonActionPerformed

private void txtLocationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLocationFocusGained
    txtLocation.setCaretPosition(0);
    txtLocation.selectAll();
}//GEN-LAST:event_txtLocationFocusGained

private void chkDSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDSTActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_chkDSTActionPerformed

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

    DlgLocation dlgLocation = new DlgLocation(this, true);
    dlgLocation.setLocationRelativeTo(this);
    dlgLocation.setVisible(true);
}//GEN-LAST:event_btnSearchActionPerformed

private void txtLocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLocationFocusLost

    txtLocationActionPerformed(null);
}//GEN-LAST:event_txtLocationFocusLost

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    btnCancelActionPerformed(null);
}//GEN-LAST:event_formWindowClosing

private void txfLatitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfLatitudeFocusGained

    txfLatitude.setCaretPosition(0);
}//GEN-LAST:event_txfLatitudeFocusGained

private void txfLongitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfLongitudeFocusGained

    txfLongitude.setCaretPosition(0);
}//GEN-LAST:event_txfLongitudeFocusGained

private void txfDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfDateFocusGained

    txfDate.setCaretPosition(0);
}//GEN-LAST:event_txfDateFocusGained

private void txfTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfTimeFocusGained

    txfTime.setCaretPosition(0);
}//GEN-LAST:event_txfTimeFocusGained

private void txfTimeZoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfTimeZoneFocusGained

    txfTimeZone.setCaretPosition(0);
}//GEN-LAST:event_txfTimeZoneFocusGained

private void txfDSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDSTActionPerformed

    txfDST.setCaretPosition(0);
}//GEN-LAST:event_txfDSTActionPerformed

private void txfMoonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfMoonFocusGained

    txfMoon.setCaretPosition(0);
}//GEN-LAST:event_txfMoonFocusGained

private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained

    txtName.setCaretPosition(0);
    txtName.selectAll();
}//GEN-LAST:event_txtNameFocusGained

private void chkTimeZoneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkTimeZoneItemStateChanged
    if (evt.getStateChange() == ItemEvent.DESELECTED) {        
        txfTimeZone.setEnabled(false);
    } else {        
        txfTimeZone.setEnabled(true);
    }

}//GEN-LAST:event_chkTimeZoneItemStateChanged

private void chkTimeZoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTimeZoneActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_chkTimeZoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chkDST;
    private javax.swing.JCheckBox chkMoon;
    private javax.swing.JCheckBox chkTimeZone;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblLongitude1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlDateAndTime;
    private javax.swing.JPanel pnlLocation;
    private javax.swing.JPanel pnlName;
    private javax.swing.JPanel pnlRemarks;
    private javax.swing.JPanel pnlTimeZoneAndMoon;
    private javax.swing.JScrollPane scrRemarks;
    private javax.swing.JTextArea txaRemarks;
    private javax.swing.JFormattedTextField txfDST;
    private javax.swing.JFormattedTextField txfDate;
    private javax.swing.JFormattedTextField txfLatitude;
    private javax.swing.JFormattedTextField txfLongitude;
    private javax.swing.JFormattedTextField txfMoon;
    private javax.swing.JFormattedTextField txfTime;
    private javax.swing.JFormattedTextField txfTimeZone;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
